---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkding-secrets
  namespace: linkding
spec:
  encryptedData:
    password: AgAbVeGsHGV2+s7PwhNZo9S/H7a5QtuSydvmoBXyxko1EXmpgGbINyR4Ik+5ecMMdgYICNCkrYY+6g2kmwFDDUwr+qN4OxoTnXtyG2t2Je552j6BeS4ig85i9GHnu8zbR0RJMDoaxO8eTJueE7cZ8eZEzXXCHxsedccmkGprcNhFGBf2y5LgJvszqyoIhZgeekZlCtcF2CHKMBEboszpE+g+o/W4fH1bsK51rXT/nPpr+O9DOwU1ZB+wfL6VZtWGxtIHE96380gvu8fucZIpEJdGJpyq0BmecPSB3vE7HOQ3rZy5dguVlgPjiMaRfEe6mzxQJjyfYb1oxCOUHgExDpx6D2WvyIaIxsNu6OCMYVnna6qfUV9MlPua4VjHBxOFzx50hO1OrZo2sSC44Y9TAD7tkTupn/C0CRtC5IrmWb3rRRvkJ7QYXosSYsDypCb1xwUZWJxYLG0fT5crEpugtQIZp2FR7AdaXQHNDCshiRIORY/LLlXSr4AHImXDPfzAQG+4kRyelOk7AzBwlCjwjaq9+kgWWxrSOOf8fBML9GOqvWMVgU9VkHnJgIAZOFwz62yWdFNTFn0+9Qiy7VUHTIabBq+UHjb2cooF3DjP7r/wOxpsePwRXsCFNPJUhnHRKbWqC7H2PsOjWrc4mFSTQOCaL47hoAFo4L0PDuhXmkcRGM+qr85B8YuKPUFsPsPbMQvtAcmzziEwiHtsEI8SaT9PjR+8Nw==
    username: AgDNGIttOS4Jb2KtAY2EvVRqep4lkjRI1qwhSAneApZm9Z+l1qzfj6DiKEWPRuK1SM10G4B7b0arVb5pdVs+EYL8z6av6B5LucUKCRUHguqlRfJDCTOTQByBd3cOECK3eVGj1gKAYSv/vg6ZLr6krTvPDKkN1m5xx0uhF64+E8uvR0xrJJ0bB3J63tOEIjgkGTq+9rYKhq3aWigt7lwXokVyDGgLbrckt4iPro6nziYHWT4KWM7bYsfa47x8VUgpx0ZVsA7uLWTDbIYf9Wx6L3kNVZhMlmvx6uc2GzbGbk2O4EtsrU5W2YY1dpsUgfx5DfLQgmE0ZrB53KXpNwa/nBTvGFY7dDb6rNC6BeUI2/8qQzt9QMaumihtIdEW5W8xPzO1S3eJxmGiVIWFaMgy0yeACb/UfuK+A5/m8RCSqISrkWxHCLd7c2y0wCynSrMI8Bb9QVC/mW1t5QSBEdHApDlgcy0rQwYTU5DQMPigB3ejj4hf+e9SrVFkuu3XZv6kGrOATxW5jZgqCz/jf149y+5PrRSqdSp+x/1cGG6RAWFUE3+as8UF56SjKF9TOboYvHp31zDk8Lg/3zzz9HjHeKNlntk3RctOmEYodeYDpDvzRFgA9OWwAO3FKcw+l4qch8FKRnPLR4wtiKaD1dnF9Vyjvb+SPQaaaxXEzOXieHMze5W5yeXWpi3Z9gCVE574ng5O566M
  template:
    metadata:
      creationTimestamp: null
      name: linkding-secrets
      namespace: linkding
    type: Opaque
