apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd

spec:
  project: applications
  source:
    repoURL: https://git.sr.ht/~tillmzw/k8s
    targetRevision: master
    path: gitops/charts/privatebin
    helm:
      values: |
        domain: bin.512.ch
        cert_issuer: letsencrypt-prod
        namespace: privatebin
  destination:
    server: https://kubernetes.default.svc
    namespace: privatebin
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
