apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: infrastructure
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "till@meyerzuwestram.net"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
