apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: https://charts.longhorn.io/
    chart: longhorn
    targetRevision: v1.7.2
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        namespaceOverride: infrastructure
        persistence:
          defaultClassReplicaCount: 1
        longhornUI:
          replicas: 1
        csi:
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1
        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
