apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: applications
  source:
    repoURL: https://github.com/tillmzw/k8s.git
    targetRevision: master
    path: gitops/charts/privatebin
    helm:
      values: |
        domain: bin.512.ch
        cert_issuer: letsencrypt-prod
        namespace: privatebin
  destination:
    server: https://kubernetes.default.svc
    namespace: privatebin
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
