apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Applications"
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: '*'
  sourceRepos:
    - 'https://github.com/tillmzw/k8s.git'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - kind: 'Secret'
  syncWindows:
    - kind: allow
      schedule: '0 4 * * *'
      duration: '2h'
      manualSync: true
      applications: 
        - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Infrastructure components"
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: 'infrastructure'
    - server: 'https://kubernetes.default.svc'
      namespace: 'argocd'
    - server: 'https://kubernetes.default.svc'
      namespace: 'kube-system'
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  syncWindows:
    - kind: allow
      schedule: '0 2 * * *'
      duration: '2h'
      manualSync: true
      applications: 
        - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure
  source:
    repoURL: https://github.com/tillmzw/k8s.git
    targetRevision: master
    path: gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
