# - create/update a htpasswd file: htpasswd -c auth foo
# - create a secret from it: kubectl create secret generic basic-auth --from-file=auth --dry-run=client -o yaml > secret.yaml
# - kubeseal it: ../../../utils/seal.sh secret.yaml 
# - commit sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: files
spec:
  encryptedData:
    auth: AgAqwJXinWpdwIYaZgg35XEWt6dx+hdis5jAkNw71+ck9qW0a5lgCyTqeM11VhLQGIslQatCHR0DZMnN/45rY88d+AlvO7gQ5G1NTVZz209jugav4iAS3mT9EDvc+TZTLOLHSnFE3iZUVioF/IlCe39+85m5jHi75/q/PnvuQdPU4FpzmWjG5zrGS0L76TsPMS7zBOtfdI7kgRLP0qW4oNrcMmpoIDfwEbblbgRUNtWpHsiw6Jc7lGh86NabQCZcCYm83oWDkOjKV54Knh4NQ3Giv7tK41nI0JuuQT7guK/Oq+BbauMb+L6D0W2WR6aWEUweT/FuzsBNdapTQOTYHLKvtikZbjqC3+Cuy3/IybzWikVCBYPB6ZgEl1j2gZvE+HbmQHBxA5bRlirEhesrTVrbzY8piUTWF4jPJTIq1/R9ZWoIs2wXhVPSQmJDxiZ7diPjKs6dTAtaMkePKnKRPLhYU7maN/wP1QYruZGP1Xz5iVHoJXa/mgB0s43PP0RsF2B2a84+qEmTVr/GzM+4zqcNJ/sTbUcDhqs0CuWutlRyeHpdlAmDjy9yFLiquSjMkoW0knNbsVx8QYQKUUL2FBW1u+0vJu76gvg5PjnwWyhBJFHUUXJta+ZIoAc3SzapG/s9thkE3VsayW/kF76Sz0LPrbg1FjG0uSmgJL/vQxW52cV6otTzJ4mC0pvliWKhWTecmx3M8QKfxH1Ns16OLaUYyPEUPWuwg0zlOAkToscMAIjoAihM68jfCdL8
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: files
