# - create/update a htpasswd file: htpasswd -c auth foo
# - create a secret from it: kubectl create secret generic basic-auth --namespace=files --from-file=auth --dry-run=client -o yaml > secret.yaml
# - kubeseal it: ../../../utils/seal.sh secret.yaml
# - commit sealed-secret.yaml

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: files
spec:
  encryptedData:
    auth: AgBOrX0j5Ae3ZOWyzVG6GqyY4wDIWIiKaP1qB+65pBObsYxAdKl6GG0yAZSlcr7Mp+Rd5cA2JW8sPVS3oLZt9khETtDJdeQ7cFdjlCKGOTCoSQwig/lz1FGXTiN9UosProG5h+l+GtdGY7u57s2tsmrU12Z5a07Vsap66YY3FPHMsXkMXKNCtap7Nz/ub/C+suDz/Fr7WZDO5rNyQDqW9jwUBvCvotx++dH/R2qL9vqxyxn77Z4cLFrySaSZYjSoXGNI8rOE/PkBMObiBe+CiRMyCqlgs6OVOzeb2wkXfmMOvrEfflySnKK7pUDPsF2mMsMtYFi3DaTPi6OWt1F8B8oZMVUNwTj78W/88q/lWy/If+yriPsQ0yWpIMSJ/GoEShmDcSFcBVv8l+bqqkOqn0MFdCo/7Q0zvCpC/dvJ/4Ps5jx6c7ALWQWFcTv5sL0nH4MWy9wG5d6TyPXKNOiCKgMyxYnr+f9VTTrk+gyQ2Z5iefSSd7atmQSwNywEvwJHKOAICaCPUMDZs4j3XhH50YsgJFwtTTGEZWoP4KHdolTUw8A2uO388h3rNSedeQMlW6Z4TNI5mASeleADvG2DrgEvetQOFIqToRCq2eMjXhHRP2c4snQlSQ3N56tdvZVV6nGQhHiBd7yp1gC15X9bmsOcQz0kX+x8OswuKuhtxjNChH6JQZiEkZN6FGtOnaEvBSFcwnuyBetPIEeJ+mAHRNEE8sbH12Udu8A8h+yMDdc73tfG/DcvGMb27x8G
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: files
