apiVersion: v1
kind: Service
metadata:
  name: files-serve
spec:
  selector:
    app: files
  ports:
  - port: 80
    name: port-serve
---
apiVersion: v1
kind: Service
metadata:
  name: files-metube
spec:
  selector:
    app: files
  ports:
  - port: 8081
    name: port-metube