apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/tillmzw/k8s.git
        revision: HEAD
        directories:
          - path: gitops/infrastructure/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: "infrastructure"
      source:
        repoURL: https://github.com/tillmzw/k8s.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: infrastructure
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: "Infrastructure components"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "infrastructure"
    - server: "https://kubernetes.default.svc"
      namespace: "argocd"
    - server: "https://kubernetes.default.svc"
      namespace: "kube-system"
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - kind: allow
      schedule: "0 2 * * *"
      duration: "2h"
      manualSync: true
      applications:
        - "*"
