configs:
  cm:
    url: https://argo.512.ch
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    hostname: argo.512.ch
    tls: true
    ingressClassName: nginx 
  # certificate:
  #   enabled: true
  #   secretName: argocd-server-tls
  #   domain: argo.512.ch
  #   issuer:
  #     group: cert-manager.io
  #     kind: ClusterIssuer
  #     name: letsencrypt-prod
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 250Mi
controller:
  args:
    statusProcessors: 10
    operationProcessors: 2
    appResyncPeriod: 300
    selfHealTimeout: 10
    repoServerTimeoutSeconds: 120 
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
    requests:
      cpu: 50m
      memory: 250Mi