server:
  ingress:
    enabled: true
    hostname: argo.512.ch
    tls: true
  config:
    url: https://argo.512.ch
  extraArgs:
    - --insecure
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 250Mi
controller:
  args:
    statusProcessors: 10
    operationProcessors: 2
    appResyncPeriod: 300
    selfHealTimeout: 10
    repoServerTimeoutSeconds: 120 
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
    requests:
      cpu: 50m
      memory: 250Mi