namespaceOverride: infrastructure
persistence:
  defaultClassReplicaCount: 1
longhornUI:
  replicas: 1
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
ingress:
  enabled: true
  host: storage.512.ch
  tls: false