apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: "Infrastructure components"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "infrastructure"
    - server: "https://kubernetes.default.svc"
      namespace: "argocd"
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - kind: allow
      schedule: "0 2 * * *"
      duration: "2h"
      manualSync: true
      applications:
        - "*"
